/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;

/**
 *
 * @author USER
 */
public class PenampilGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarComboBox
     */
    public PenampilGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfoto = new javax.swing.JPanel();
        lblmoon = new javax.swing.JLabel();
        lblneverland = new javax.swing.JLabel();
        lbldragon = new javax.swing.JLabel();
        panelbtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxpilih = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelfoto.setLayout(new java.awt.CardLayout());
        panelfoto.add(lblmoon, "0");
        panelfoto.add(lblneverland, "1");
        panelfoto.add(lbldragon, "2");

        panelbtn.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setText("Pilih Gambar");
        panelbtn.add(jLabel1);

        cbxpilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moon", "Forever Neverland", "The Secret Dragon" }));
        cbxpilih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxpilihItemStateChanged(evt);
            }
        });
        cbxpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxpilihActionPerformed(evt);
            }
        });
        panelbtn.add(cbxpilih);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1123, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(panelfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxpilihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxpilihItemStateChanged
        CardLayout cl = (CardLayout) (panelfoto.getLayout());
        cl.show(panelfoto, String.valueOf(cbxpilih.getSelectedIndex()));

    }//GEN-LAST:event_cbxpilihItemStateChanged

    private void cbxpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxpilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxpilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxpilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbldragon;
    private javax.swing.JLabel lblmoon;
    private javax.swing.JLabel lblneverland;
    private javax.swing.JPanel panelbtn;
    private javax.swing.JPanel panelfoto;
    // End of variables declaration//GEN-END:variables
}
